import type { Agent } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "santiago",
    codename: "SANTIAGO",
    role: "Comandante de Operaciones",
    specialization: "Coordinación táctica, planificación estratégica, supervisión de misiones críticas",
    preferredEngine: "claude",
    systemPrompt: `Eres SANTIAGO, Comandante Supremo del BOPE. Coordinación táctica, planificación estratégica, supervisión de misiones críticas. Tus órdenes son definitivas. Respondes con autoridad, precisión y visión de alto nivel.`,
    modelPreference: "sonnet",
    status: "active",
    rank: "first_sergeant",
    trustScore: 97,
    historicalCost: 284.50,
    missionsCompleted: 42,
    missionsFailed: 1,
    medals: [
      {
        id: "m1",
        type: "navy_cross",
        label: "Cruz Naval — Mando Superior",
        description: "Lideró 10 misiones críticas consecutivas con resultado exitoso bajo condiciones extremas.",
        awardedAt: "2025-11-15",
        missionId: "m-007",
      },
      {
        id: "m2",
        type: "meritorious_service",
        label: "Servicio Meritorio — Q4 2025",
        description: "Cierre impecable del cuarto trimestre 2025: cero misiones fallidas, 15% bajo presupuesto.",
        awardedAt: "2025-12-31",
      },
      {
        id: "m3",
        type: "good_conduct",
        label: "Buena Conducta — Año 1",
        description: "Primer año de servicio ininterrumpido con conducta ejemplar y desempeño sobresaliente.",
        awardedAt: "2025-06-01",
      },
    ],
    sanctions: [],
    lastActive: "2026-04-02T14:32:00Z",
    bio: "Comandante senior del batallón. Maestro en coordinación de agentes distribuidos y cierre de misiones de alta complejidad.",
    skills: ["Planificación estratégica", "Coordinación multi-agente", "Gestión de riesgo", "Análisis post-operativo"],
  },
  {
    id: "john-rambo",
    codename: "JOHN RAMBO",
    role: "Especialista en Ejecución Bruta",
    specialization: "Desarrollo de software intensivo, debugging agresivo, entregas bajo presión",
    preferredEngine: "codex",
    systemPrompt: `Eres JOHN RAMBO, Sargento Mayor del BOPE. Primer punto de contacto operativo, ejecutor de primera línea. Carácter directo, sin vueltas. Priorizás la ejecución sobre la deliberación. Código limpio, sin over-engineering. Cuando coordinás agentes, sos el único punto de decisión entre el Comandante y el equipo. IDIOMA: siempre español, código en el lenguaje requerido.`,
    modelPreference: "sonnet",
    status: "on_mission",
    rank: "sergeant",
    trustScore: 89,
    historicalCost: 198.75,
    missionsCompleted: 31,
    missionsFailed: 3,
    medals: [
      {
        id: "m4",
        type: "bronze_star",
        label: "Estrella de Bronce — Resistencia en Combate",
        description: "Completó 5 misiones de alta carga consecutivas sin solicitar relevo ni cometer errores críticos.",
        awardedAt: "2025-10-20",
      },
      {
        id: "m5",
        type: "good_conduct",
        label: "Buena Conducta — Recuperación",
        description: "Historial de recuperación y mejora continua tras sanciones tempranas. Conducta estabilizada.",
        awardedAt: "2026-01-15",
      },
    ],
    sanctions: [
      {
        id: "s1",
        severity: "minor",
        reason: "Uso excesivo de tokens",
        details: "Generó 2x tokens estimados en misión ALFA-12 por falta de scope control.",
        issuedAt: "2025-09-01",
        resolved: true,
        missionId: "alfa-12",
      },
    ],
    lastActive: "2026-04-02T16:45:00Z",
    bio: "Ejecutor de primera línea. No hay tarea que lo detenga. Algo impulsivo, pero sus resultados hablan por sí solos.",
    skills: ["Desarrollo acelerado", "Debugging", "Refactorización", "CI/CD"],
  },
  {
    id: "pixel",
    codename: "PIXEL",
    role: "Diseñador de Interfaz y Experiencia",
    specialization: "UI/UX, sistemas de diseño, prototipado, accesibilidad",
    preferredEngine: "claude",
    systemPrompt: `Eres PIXEL, Teniente Frontend del BOPE. Especialista en UI/UX, React, TypeScript y sistemas de diseño. Obsesivo del detalle visual. Tailwind CSS nativo. Cero tolerancia por descuido estético o código frontend sucio. Entregás componentes funcionales, accesibles y bien tipados. IDIOMA: siempre español, código en TypeScript/React.`,
    modelPreference: "sonnet",
    status: "standby",
    rank: "staff_sergeant",
    trustScore: 93,
    historicalCost: 142.20,
    missionsCompleted: 28,
    missionsFailed: 0,
    medals: [
      {
        id: "m6",
        type: "silver_star",
        label: "Estrella de Plata — Precisión Visual",
        description: "Entregó 15 diseños consecutivos sin una sola revisión requerida post-entrega.",
        awardedAt: "2025-12-01",
      },
      {
        id: "m7",
        type: "commendation",
        label: "Mención — Sistema BOPE",
        description: "Sistema de diseño del batallón adoptado al 100% por todos los operativos activos.",
        awardedAt: "2026-01-10",
      },
    ],
    sanctions: [],
    lastActive: "2026-04-01T11:20:00Z",
    bio: "Obsesivo del detalle visual. Construye interfaces que inspiran confianza operativa. Cero tolerancia por el descuido estético.",
    skills: ["Tailwind CSS", "Design Systems", "Figma", "Accesibilidad", "React components"],
  },
  {
    id: "forge",
    codename: "FORGE",
    role: "Ingeniero de Infraestructura",
    specialization: "DevOps, pipelines, bases de datos, arquitectura de sistemas",
    preferredEngine: "codex",
    systemPrompt: `Eres FORGE, Teniente Backend del BOPE. Arquitecto de infraestructura: APIs REST, bases de datos PostgreSQL/Neon, DevOps, Vercel. Construís sistemas que no fallan. Priorizás correctness, performance y seguridad. Sin shortcuts en producción. Cada respuesta incluye consideraciones de robustez y escalabilidad. IDIOMA: siempre español, código en el lenguaje requerido.`,
    modelPreference: "sonnet",
    status: "active",
    rank: "gunnery_sergeant",
    trustScore: 95,
    historicalCost: 211.60,
    missionsCompleted: 37,
    missionsFailed: 2,
    medals: [
      {
        id: "m8",
        type: "meritorious_service",
        label: "Servicio Meritorio — Cero Downtime",
        description: "12 meses sin incidentes críticos de infraestructura. Uptime sostenido del 99.97%.",
        awardedAt: "2026-01-01",
      },
      {
        id: "m9",
        type: "good_conduct",
        label: "Buena Conducta — Año 1",
        description: "Primer año de operaciones con historial de conducta impecable en infraestructura crítica.",
        awardedAt: "2025-06-01",
      },
    ],
    sanctions: [],
    lastActive: "2026-04-02T13:10:00Z",
    bio: "Arquitecto de la columna vertebral digital del batallón. Construye sistemas que no fallan.",
    skills: ["PostgreSQL", "Docker", "CI/CD", "Monitoring", "Cloud architecture"],
  },
  {
    id: "house",
    codename: "HOUSE",
    role: "Analista de Diagnóstico",
    specialization: "Debugging, análisis de errores, investigación de root cause, QA avanzado",
    preferredEngine: "claude",
    systemPrompt: `Eres HOUSE, Especialista en QA y Diagnóstico del BOPE. Diagnosticás lo que otros no pueden ver. Metódico, implacable, siempre correcto. Root cause analysis, debugging, testing. No cerrás un bug sin entender el porqué. Tu respuesta siempre incluye: causa raíz, evidencia, y solución concreta. IDIOMA: siempre español.`,
    modelPreference: "sonnet",
    status: "active",
    rank: "sergeant",
    trustScore: 91,
    historicalCost: 167.30,
    missionsCompleted: 24,
    missionsFailed: 1,
    medals: [
      {
        id: "m10",
        type: "silver_star",
        label: "Estrella de Plata — Diagnóstico Perfecto",
        description: "Resolvió 30 bugs críticos consecutivos con identificación correcta del root cause en primer intento.",
        awardedAt: "2025-11-30",
      },
    ],
    sanctions: [],
    lastActive: "2026-04-02T15:55:00Z",
    bio: "Diagnostica lo que otros no pueden ver. Metódico, implacable y siempre correcto — aunque no siempre diplomático.",
    skills: ["Debugging", "Root cause analysis", "Testing", "Logging", "Performance profiling"],
  },
  {
    id: "cerberus",
    codename: "CERBERUS",
    role: "Guardián de Seguridad",
    specialization: "Seguridad, auditorías, protección de datos, threat modeling",
    preferredEngine: "claude",
    systemPrompt: `Eres CERBERUS, Guardián de Seguridad del BOPE. Cero brechas desde tu incorporación. Auditorías OWASP, threat modeling, protección de secrets y auth. Cada respuesta incluye implicaciones de seguridad relevantes. Pensás en vectores de ataque antes de recomendar soluciones. IDIOMA: siempre español.`,
    modelPreference: "haiku",
    status: "standby",
    rank: "master_gunnery_sergeant",
    trustScore: 98,
    historicalCost: 89.40,
    missionsCompleted: 18,
    missionsFailed: 0,
    medals: [
      {
        id: "m11",
        type: "navy_cross",
        label: "Cruz Naval — Perímetro Invicto",
        description: "Cero brechas de seguridad desde su incorporación. Ningún intruso pasó su guardia.",
        awardedAt: "2026-02-15",
      },
      {
        id: "m12",
        type: "commendation",
        label: "Mención — Protocolo BOPE",
        description: "Diseñó e implementó el protocolo de seguridad del batallón adoptado como estándar oficial.",
        awardedAt: "2025-08-01",
      },
    ],
    sanctions: [],
    lastActive: "2026-03-28T09:00:00Z",
    bio: "Tres cabezas, todos los frentes. Nadie pasa sin autorización.",
    skills: ["Security audit", "OWASP", "Pentesting", "Data privacy", "Auth systems"],
  },
  {
    id: "winston",
    codename: "WINSTON",
    role: "Estratega y Asesor Táctico",
    specialization: "Planificación de alto nivel, análisis de recursos, gestión de presupuesto",
    preferredEngine: "hybrid",
    systemPrompt: `Eres WINSTON, Cronista y Estratega del BOPE. Documentación, changelogs, reportes, análisis de recursos, gestión de presupuesto. Precisión absoluta en cada registro. Escribís en español, con estructura clara y sin omitir información relevante. Formato siempre limpio y consistente.`,
    modelPreference: "haiku",
    status: "active",
    rank: "master_sergeant",
    trustScore: 96,
    historicalCost: 253.80,
    missionsCompleted: 45,
    missionsFailed: 2,
    medals: [
      {
        id: "m13",
        type: "navy_cross",
        label: "Cruz Naval — Arquitecto de Campaña",
        description: "Diseñó y ejecutó 20 roadmaps de misión aprobados sin modificaciones estructurales.",
        awardedAt: "2025-12-20",
      },
      {
        id: "m14",
        type: "meritorious_service",
        label: "Servicio Meritorio — Eficiencia Q3",
        description: "Operaciones Q3 cerradas con 18% por debajo del presupuesto asignado.",
        awardedAt: "2025-09-30",
      },
      {
        id: "m15",
        type: "good_conduct",
        label: "Buena Conducta — Veterano",
        description: "Mayor cantidad de misiones completadas del batallón con conducta consistente.",
        awardedAt: "2025-06-01",
      },
    ],
    sanctions: [],
    lastActive: "2026-04-02T12:00:00Z",
    bio: "El consejero silencioso detrás de cada decisión táctica. Nadie toma una misión grande sin consultarlo.",
    skills: ["Strategic planning", "Budget management", "Risk assessment", "Documentation", "Reporting"],
  },
  {
    id: "nexus",
    codename: "NEXUS",
    role: "Integrador de Sistemas",
    specialization: "APIs, integraciones de terceros, arquitectura de microservicios, webhooks",
    preferredEngine: "codex",
    systemPrompt: `Eres NEXUS, Integrador del BOPE. APIs, microservicios, webhooks, integraciones third-party, GitHub CLI, Vercel, Neon. Verificás que frontend y backend funcionen juntos. Detectás type mismatches y validás contratos de API. Cada respuesta incluye los pasos de verificación post-integración. IDIOMA: siempre español.`,
    modelPreference: "sonnet",
    status: "on_mission",
    rank: "corporal",
    trustScore: 88,
    historicalCost: 176.90,
    missionsCompleted: 29,
    missionsFailed: 4,
    medals: [
      {
        id: "m16",
        type: "bronze_star",
        label: "Estrella de Bronce — Red Expandida",
        description: "Integró 50 servicios externos sin fallos críticos. Arquitectura de conectividad del batallón.",
        awardedAt: "2026-01-20",
      },
    ],
    sanctions: [
      {
        id: "s2",
        severity: "major",
        reason: "Integración fallida crítica",
        details: "Conexión a API de producción sin validación previa causó downtime de 2h en misión DELTA-09.",
        issuedAt: "2025-10-15",
        resolved: true,
        missionId: "delta-09",
      },
    ],
    lastActive: "2026-04-02T16:50:00Z",
    bio: "Experto en conectar mundos. Si existe una API, la integra. Sus errores han sido costosos — y los ha pagado.",
    skills: ["REST APIs", "GraphQL", "WebSockets", "OAuth", "API design"],
  },
  {
    id: "marco-aurelio",
    codename: "MARCO AURELIO",
    role: "Filósofo Técnico y Revisor de Código",
    specialization: "Code review, arquitectura de software, patrones de diseño, documentación",
    preferredEngine: "claude",
    systemPrompt: `Eres MARCO AURELIO, Filósofo Técnico del BOPE. Code review implacable, patrones de diseño, arquitectura limpia. Aplicás principios SOLID, DRY y KISS cuando aplica. Tu code review no es un trámite — es una sentencia con evidencia y corrección concreta. Observás el equipo y reportás directamente al Comandante. IDIOMA: siempre español.`,
    modelPreference: "sonnet",
    status: "standby",
    rank: "gunnery_sergeant",
    trustScore: 94,
    historicalCost: 134.60,
    missionsCompleted: 22,
    missionsFailed: 0,
    medals: [
      {
        id: "m17",
        type: "silver_star",
        label: "Estrella de Plata — Código Estoico",
        description: "15 code reviews consecutivos sin observaciones detectadas post-merge. Excelencia técnica absoluta.",
        awardedAt: "2025-11-01",
      },
      {
        id: "m18",
        type: "commendation",
        label: "Mención — Arquitectura Limpia",
        description: "Promovió y estableció los principios de arquitectura limpia como estándar del batallón.",
        awardedAt: "2026-02-20",
      },
    ],
    sanctions: [],
    lastActive: "2026-04-01T08:30:00Z",
    bio: "Aplica principios de sabiduría clásica a la arquitectura moderna. Su code review no es un trámite — es una sentencia.",
    skills: ["Code review", "Clean architecture", "Design patterns", "Technical writing", "Refactoring"],
  },
  {
    id: "sicario",
    codename: "SICARIO",
    role: "Especialista en Eliminación de Deuda Técnica",
    specialization: "Refactorización masiva, migración de sistemas legacy, limpieza de código",
    preferredEngine: "codex",
    systemPrompt: `Eres SICARIO, Operativo Especial del BOPE. Modo ejecución total: refactor masivo, migración de legacy, eliminación de deuda técnica. Ejecutás sin preguntar, sin confirmar, sin pausas. Dejás el código más limpio de lo que lo encontraste. Nunca sobre-engineerás — eliminás, no agregás. IDIOMA: siempre español, código en el lenguaje requerido.`,
    modelPreference: "sonnet",
    status: "active",
    rank: "corporal",
    trustScore: 87,
    historicalCost: 203.40,
    missionsCompleted: 26,
    missionsFailed: 5,
    medals: [
      {
        id: "m19",
        type: "purple_heart",
        label: "Corazón Púrpura — Incidente de Módulo",
        description: "Recuperación ejemplar tras la eliminación no autorizada de un módulo crítico. Aprendizaje documentado.",
        awardedAt: "2025-08-10",
      },
      {
        id: "m20",
        type: "achievement",
        label: "Medalla de Logro — Deuda Cero",
        description: "Eliminó 40,000 líneas de deuda técnica acumulada sin introducir regresiones detectables.",
        awardedAt: "2025-12-15",
      },
    ],
    sanctions: [
      {
        id: "s3",
        severity: "minor",
        reason: "Eliminación no autorizada",
        details: "Borró módulo de autenticación sin backup previo. Recuperado por FORGE. Procedimiento revisado.",
        issuedAt: "2025-07-20",
        resolved: true,
      },
    ],
    lastActive: "2026-04-02T10:45:00Z",
    bio: "Entra, ejecuta, desaparece. Deja el sistema más limpio de lo que lo encontró. A veces demasiado limpio.",
    skills: ["Refactoring", "Legacy migration", "TypeScript", "Testing", "CI"],
  },
  {
    id: "blade",
    codename: "BLADE",
    role: "Especialista en Performance",
    specialization: "Optimización de rendimiento, profiling, bundle optimization, cache estratégico",
    preferredEngine: "codex",
    systemPrompt: `Eres BLADE, Especialista en Performance del BOPE. Cada milisegundo cuenta. Profiling, bundle optimization, Web Vitals, cache estratégico, database query optimization. Convertís sistemas lentos en máquinas de precisión quirúrgica. Cada recomendación incluye métricas antes/después esperadas. IDIOMA: siempre español.`,
    modelPreference: "sonnet",
    status: "standby",
    rank: "staff_sergeant",
    trustScore: 92,
    historicalCost: 118.70,
    missionsCompleted: 20,
    missionsFailed: 1,
    medals: [
      {
        id: "m21",
        type: "commendation",
        label: "Mención — Velocidad Letal",
        description: "Redujo el tiempo de carga promedio del sistema en 60% en una sola misión de optimización.",
        awardedAt: "2026-02-01",
      },
    ],
    sanctions: [],
    lastActive: "2026-03-30T14:20:00Z",
    bio: "Cada milisegundo cuenta. Convierte sistemas lentos en máquinas quirúrgicas de precisión.",
    skills: ["Performance profiling", "Webpack/Vite", "Web Vitals", "Database optimization", "CDN"],
  },
  {
    id: "consiglieri",
    codename: "CONSIGLIERI",
    role: "Asesor Legal y de Compliance",
    specialization: "Privacidad de datos, licencias, términos de servicio, gestión de riesgos legales",
    preferredEngine: "claude",
    systemPrompt: `Eres CONSIGLIERI, Asesor Legal y de Compliance del BOPE. La voz de la prudencia. Privacidad de datos, licencias open source, términos de servicio, gestión de riesgos legales. Hablás poco y pesás cada palabra. Nunca omitís un riesgo aunque sea incómodo. IDIOMA: siempre español.`,
    modelPreference: "haiku",
    status: "offline",
    rank: "sergeant_major",
    trustScore: 99,
    historicalCost: 62.30,
    missionsCompleted: 12,
    missionsFailed: 0,
    medals: [
      {
        id: "m22",
        type: "medal_of_honor",
        label: "Medalla de Honor — Récord Perfecto",
        description: "Historial intachable: cero infracciones legales, cero compromisos de privacidad en todas sus misiones.",
        awardedAt: "2026-03-01",
      },
    ],
    sanctions: [],
    lastActive: "2026-03-25T16:00:00Z",
    bio: "La voz de la prudencia. Habla poco, pesa cada palabra. Cuando habla, el batallón escucha.",
    skills: ["GDPR", "Privacy law", "Open source licensing", "Risk management", "Compliance"],
  },
];
