/**
 * BOPE Orchestrator — Type contracts
 * PlanV1: contract generated by JOHN (Codex CLI) as planner/dispatcher.
 */

export type Engine = 'codex' | 'claude';

export interface PlanTask {
  id: string;
  title: string;
  engine: Engine;
  agent?: string;
  instructions: string;
  /** Override branch name; defaults to mission/<mission_id>/<task_id> */
  branch?: string;
}

export interface PlanMerge {
  strategy: 'john-integrates';
  base: string;
}

export interface PlanV1 {
  parallelism?: number;
  tasks: PlanTask[];
  merge?: PlanMerge;
}

// ─── Event shapes sent to POST /api/v1/missions/:id/events ───────────────────

export type EventKind =
  | 'ORDER'
  | 'REPORT'
  | 'SUGGESTION'
  | 'REQUEST_HELP'
  | 'TOOL_CALL'
  | 'TOOL_RESULT'
  | 'APPROVAL_REQUEST';

export type EventDirection = 'DOWN' | 'UP' | 'LATERAL';
export type EventPriority = 'P0' | 'P1' | 'P2' | 'P3';
export type EventStatus =
  | 'PENDING'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'BLOCKED'
  | 'CANCELLED';

export interface EventPayload {
  task_id?: string;
  from_agent: string;
  to_agent: string;
  direction: EventDirection;
  kind: EventKind;
  priority?: EventPriority;
  status?: EventStatus;
  summary?: string;
  payload?: Record<string, unknown>;
  evidence?: Record<string, unknown>;
  requires_approval?: boolean;
}

// ─── CLI options ──────────────────────────────────────────────────────────────

export interface OrchestratorOptions {
  mission: string;
  baseUrl: string;
  repo: string;
  baseBranch: string;
}
